language: node_js
node_js:
  - 14
services:
  - mongodb
notifications:
  email: false
deploy:
  provider: heroku
  app: random-asian-api
  api_key:
    secure: yZYuZo8pLYdV/JPhDbcnOcm1kjgs5huDSkHgND+F0scBOwuwJI3Zhnp8GPEAwsvgiVCPVJYKIAyU/SrUX+Z1uPzqYPRDna9rsXpbg6UvvECyiDfmzYqDo8HyzS9W7/C0Pddb34lsdeCeAIVRafGoLTv6pqcZRD62UnSPNdsxnkejqmxNxEpJzVPj+kAP4Oge5ISAsSEUnEtYjNnjtTHeaqZzM6v/4uMKWxCXdQQYtMMeClH8q/TG/gvByp/2PgYdsKWAtYw88SU6hglRGRbqDS/p7q2HVlbBcodlSPaI8WzvLcuG9G37KP5P47sdatrd3CN4ngDrE9gc+hgJ1rder6zeBXmn7khHQe8xyrWzSSxRI2dU7U1b42dmkr+jSimwkLOgEHmfjfYsZhGlnjmG2jdy9DPDqiy0/+s7OxUsSCemk7b5bw4yWaVqu+/vQGcgeKHVdS+S/91yBJfNeTXklmowX7vYnpNhXUBI5HARBL/zh1E9RfgcbVR006fggRL0GA3Kg3bfkpI/5hvaFgNCw10eFJiB7aDndZ+tVPI3uovwtm2GR+aWHnHYSu4y8e+Ys5RgbL7l9i2sywriWhCRUrnQAXsiRQZDH4m9lBS0uNJOhpkJn1EVXnRWkSIAJgBqNNxCd6gt47ZXr+I/bZeh93y+H9duHpEPuESEs3prVxM=
